; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules
projects[admin_menu][version] = "3.0-rc5"
projects[admin_menu][subdir] = "contrib"

projects[auto_nodetitle][version] = "1.0"
projects[auto_nodetitle][patch][881170] = "https://www.drupal.org/files/issues/auto_nodetitle-881170-50.patch"
projects[auto_nodetitle][subdir] = "contrib"

projects[ctools][version] = "1.9"
projects[ctools][subdir] = "contrib"

projects[content_access][version] = "1.2-beta2"
projects[content_access][subdir] = "contrib"

projects[context][version] = "3.6"
projects[context][subdir] = "contrib"

projects[date][version] = "2.9"
projects[date][subdir] = "contrib"

projects[entity][version] = "1.6"
projects[entity][subdir] = "contrib"

projects[entityreference][version] = "1.1"
projects[entityreference][subdir] = "contrib"

projects[features][version] = "2.7"
projects[features][subdir] = "contrib"

projects[field_group][version] = "1.5"
projects[field_group][subdir] = "contrib"

projects[fullcalendar][version] = "2.0"
projects[fullcalendar][subdir] = "contrib"

projects[homebox][version] = "2.0-rc2"
projects[homebox][subdir] = "contrib"

projects[securesite][version] = "2.0-beta3"
projects[securesite][subdir] = "contrib"

projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = "contrib"

projects[token][version] = "1.6"
projects[token][subdir] = "contrib"

projects[uuid][version] = "1.0-beta1"
projects[uuid][subdir] = "contrib"

projects[uuid_features][version] = "1.0-alpha4"
projects[uuid_features][subdir] = "contrib"

projects[views][version] = "3.13"
projects[views][subdir] = "contrib"

projects[field_collection][version] = "1.0-beta10"
projects[field_collection][subdir] = "contrib"

projects[references_dialog][type] = "module"
projects[references_dialog][subdir] = "contrib"
projects[references_dialog][download][type] = "git"
projects[references_dialog][download][url] = "http://git.drupal.org/project/references_dialog.git"
projects[references_dialog][download][branch] = "7.x-1.x"
projects[references_dialog][download][revision] = "faf64b7b620746adafde56d2721155961e040df0"

libraries[fullcalendar][download][type] = get
libraries[fullcalendar][download][url]  = "https://github.com/arshaw/fullcalendar/archive/v1.5.4.tar.gz"
libraries[fullcalendar][destination]    = "libraries"
libraries[fullcalendar][directory_name] = "fullcalendar"
